#------------------------------Prefix:---------------------------------------
unbind C-b
set -g prefix C-x
bind C-x send-prefix

#Various sets

#set the base index of windows to 1
set -g base-index 1

#set mouse interaction
set -g mouse on

#Status bar customs
set -g status-bg purple
set -g status-interval 10
set -g window-status-format "[fg=green]#I: #W"
set -g window-status-current-format "#[fg=white,bg=blue]#I: #W"

#Highlight active window
#set -g window-status-current-bg blue #doesn't work

#Pane Defaults
set-option -g pane-base-index 1
set-option -g pane-border-status top

#Window Defaults
set-option -g default-terminal "screen-256color"
set-option -g allow-rename off



#------------------------------------Keybinds:--------------------------------------

#Split panes using \ and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

#access source file with r
bind r source-file ~/.config/tmux/tmux.conf

#move between panes like in vim
unbind h
unbind j
unbind k
unbind l
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -D
bind -n M-k select-pane -U

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour yellow

# copy mode
setw -g mode-style 'fg=black bg=purple bold'

# panes
set -g pane-border-style 'fg=purple'
set -g pane-active-border-style 'fg=yellow'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=purple'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=yellow'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=purple'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=purple bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

setw -g window-status-bell-style 'fg=yellow bg=purple bold'

# messages
set -g message-style 'fg=yellow bg=purple bold'

set -g status-style "bg=black,fg=white"
set -g status-left "(\uf240') #(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'percentage' | awk '{print $2}')"
